import { AddPerson } from "@/components/AddPerson";
import { CustomForm } from "@/components/CustomForm";
import Head from "next/head";
import Link from "next/link";
import { MailchimpFormContainer } from "@/components/MailchimpFormContainer";
import { useRouter } from "next/router";

export default function Home({ people }) {
  const router = useRouter();

  const handleDelete = async (id) => {
    const deleteRoute = "http://localhost:3002/people/" + id;
    if (window.confirm("Sure to delete?")) {
      const res = await fetch(deleteRoute, {
        method: "DELETE",
      });
      console.log(res, deleteRoute);
      if (res.ok) {
        alert("Deleted successfully");
        router.reload();
      } else {
        alert("Not deleted");
      }
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container homepage">
        <h1>People Data Fetching Tut</h1>
        <ul>
          {people.map((item, idx) => (
            <li key={idx} onDoubleClick={() => handleDelete(item.id)}>
              <Link href={`/person/${item.name.replace(/ /g, "-")}`} passHref>
                <h3>{item.name}</h3>
              </Link>
              <em>{item.occupation}</em>
            </li>
          ))}
        </ul>

        <AddPerson />
      </div>
      <MailchimpFormContainer />
    </>
  );
}

export const getStaticProps = async () => {
  const people = await fetch("http://localhost:3002/people")
    .then((res) => res.json())
    .catch((error) => console.log({ error }));
  return {
    props: { people },
  };
};
